#!/bin/bash

ICON=$HOME/.scripts/assets/lock.png
TMPBG=/tmp/screenshot.png
RES=$(xrandr | grep 'current' | sed -E 's/.*current\s([0-9]+)\sx\s([0-9]+).*/\1x\2/')

# import -window root $TMPBG
sleep .1 # to avoid taking a screenshot of the power menu
scrot $TMPBG

# convert -scale 10% -blur 0x4 -resize 1000% $TMPBG $TMPBG
# convert $TMPBG $ICON -gravity center -composite -matte $TMPBG
ffmpeg -f x11grab -video_size $RES -y -i $DISPLAY -i $ICON -filter_complex "boxblur=15,overlay=(main_w-overlay_w)/2:(main_h-overlay_h)/2" -vframes 1 $TMPBG -loglevel quiet

if [[ "$1" == "mute" ]]; then
	MUTED=$(dnd-manager status)
	if [[ "$MUTED" == "ON" ]]; then
		i3lock -f -t -i $TMPBG
	else
		dnd-manager -s on; i3lock -f -t -i $TMPBG -n; dnd-manager -s off
	fi
else
	i3lock -f -t -i $TMPBG
fi

rm $TMPBG
exit 0
