#!/bin/bash
# Moves the current i3wm workspace to another monitor. If it finds more than 2, displays them using rofi.
# github.com/jomifepe

function print() { echo "$1"; notify-send "$1"; }
MONITORS=$(xrandr -q | grep " connected" | cut -d" " -f1); COUNT=$(echo "$MONITORS" | wc -l)
[ "$COUNT" -eq 1 ] && print "Couldn't move workspace, only one monitor is connected" && exit 1
CURRENT_WS=($(i3-msg -t get_workspaces | jq -r 'map(select(.focused))[0] | .output, .num'))
[ "$COUNT" -eq 2 ] && i3-msg move workspace to output $(echo "$MONITORS" | grep -v "${CURRENT_WS[0]}") &> /dev/null \
	&& sleep .1 && i3-msg workspace ${CURRENT_WS[1]} &> /dev/null && exit 0
OPT=$(echo "$MONITORS" | rofi -dmenu -i -lines 5 -width 15 -p monitor | awk '{print $1}')
[ ${#OPT} -gt 0 ] && i3-msg move workspace to output $OPT || exit 1