#!/bin/bash

[ -z "$1" ] && echo "No file specified" && exit 1
[ -z "$2" ] && echo "No command specified" && exit 1

while true; do
  inotifywait -qm --event modify --format '%w' "$(realpath $1)" | $2
done