#! /bin/sh

#  ██████╗ ███████╗██████╗ ██╗    ██╗███╗   ███╗
#  ██╔══██╗██╔════╝██╔══██╗██║    ██║████╗ ████║
#  ██████╔╝███████╗██████╔╝██║ █╗ ██║██╔████╔██║
#  ██╔══██╗╚════██║██╔═══╝ ██║███╗██║██║╚██╔╝██║
#  ██████╔╝███████║██║     ╚███╔███╔╝██║ ╚═╝ ██║
#  ╚═════╝ ╚══════╝╚═╝      ╚══╝╚══╝ ╚═╝     ╚═╝

sxhkd -c "$HOME/.config/sxhkd/sxhkdrc-common" "$HOME/.config/sxhkd/sxhkdrc-bspwm" &> /tmp/sxhkd.log &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         0
bspc config window_gap          12
bspc config top_padding 		  40

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Gscreenshot state=floating
bspc rule -a "Welcome to Android Studio" state=floating

xsetroot -cursor_name left_ptr & # Changing the cursor to a pointer at startup
lxpolkit &> /tmp/lxpolkit.log &
nitrogen --restore
compton &> /tmp/compton.log &
polybar custom &> /tmp/polybar.log &
numlockx on
nm-applet &
blueman-applet &
libinput-gestures-setup start &
dropbox start &
synergy &
redshift-gtk &
