#!/bin/bash
# Used for launching the android emulator from the command line

EMULATOR_BIN=$ANDROID_HOME/emulator/emulator
ROFI="rofi -width 30 -lines 10 -dmenu -i -p option"

function print() { echo "$1"; notify-send "$1"; }

[ -z $ANDROID_HOME ] && print "Please define the ANDROID_HOME environment variable with your Android SDK path" && exit 1
[ ! -f "$EMULATOR_BIN" ] && print "Couldn't find emulator binary (https://developer.android.com/studio/run/emulator-commandline)" && exit 1

mapfile -t avds < <(emulator -list-avds)

echo
if [ ${#avds[@]} -eq 0 ]; then
	print "No android emulators found."; exit 1
elif [ ${#avds[@]} -eq 1 ]; then
	echo -e "\e[97mRunning \e[92m${avds[0]}\e[97m..."
	$EMULATOR_BIN -avd "${avds[0]}"
else
	LIST=''
	for i in "${!avds[@]}"; do
		if [ $i == 0 ]; then
			LIST="${avds[i]}"
		else
			LIST="$LIST\n${avds[i]}"
		fi
	done

	option=`echo -e $LIST | $ROFI`
	[ ! -z "$option" ] && $EMULATOR_BIN -avd "$option"	
fi
