#!/bin/bash

mapfile -t avds < <(emulator -list-avds)

echo
if [ ${#avds[@]} -eq 0 ]; then
	echo -e "\e[91mNo android emulators found."
elif [ ${#avds[@]} -eq 1 ]; then
	echo -e "\e[97mRunning \e[92m${avds[0]}\e[97m..."
	# emulator -avd "${avds[0]}" > /dev/null 2>&1 &
	emulator -avd "${avds[0]}"
else
	for i in "${!avds[@]}"; do
		echo -e "\e[97m$((i + 1))) \e[92m${avds[i]}"
	done
	
	read -p $'\e[97mChoose an emulator: ' num

	if (( $num <= 0 )) || (( $num > ${#avds[@]} )); then
		echo -e "\e[91mInvalid option"
		echo
	else
		echo -e "Running \e[92m${avds[i - 1]}\e[97m..."
		# emulator -avd "${avds[$num - 1]}" > /dev/null 2>&1 &
		emulator -avd "${avds[$num - 1]}"
	fi
fi