#!/bin/bash

mapfile -t avds < <(emulator -list-avds)

echo
if [ ${#avds[@]} -eq 0 ]; then
	echo -e "\e[91mNo android emulators found."
elif [ ${#avds[@]} -eq 1 ]; then
	echo -e "\e[97mRunning \e[92m${avds[0]}\e[97m..."
	# emulator -avd "${avds[0]}" > /dev/null 2>&1 &
	emulator -avd "${avds[0]}"
else
	LIST=''
	for i in "${!avds[@]}"; do
		if [ $i == 0 ]; then
			LIST="${avds[i]}"
		else
			LIST="$LIST\n${avds[i]}"
		fi
	done

	option=`echo -e $LIST | rofi -width 30 -dmenu -i -p option`
	[ ! -z "$option" ] && emulator -avd "$option"	
fi
