#!/bin/bash

function list_sinks()
{
   pacmd list-sinks | grep -E 'index:|name:'
}

function switch_sink_default()
{
   pacmd set-default-sink $1 || echo failed
}

function switch_sink_applications()
{
   pacmd list-sink-inputs | 
      awk '/index:/{print $2}' |
      xargs -r -I{} pacmd move-sink-input {} $1 ||
      echo failed
}

function switch_sink()
{
  switch_sink_default      "$@"
  switch_sink_applications "$@"
}

# Use a zenity gui to switch audio outputs
function switch_gui()
{
   # get current output id, all output ids and the sink names
   current_id=$(pacmd list-sinks | egrep '\* index:' | egrep -o '[0-9]+$')
   ids=($(pacmd list-sinks | egrep 'index:' | egrep -o '[0-9]+$' | tr '\n' ' '))
   names=($(pacmd list-sinks | egrep 'name:' | cut -d'.' -f2,3,4,5 | tr -d '>'))

   zen_pars="--list --radiolist --column '' --column 'ID' --column 'Sink_name'"

   # construct the zenity command
   for i in "${!ids[@]}"; do
      if [ ${ids[$i]} = $current_id ]; then
         zen_pars="$zen_pars TRUE"
      else
         zen_pars="$zen_pars FALSE"
      fi
      zen_pars="$zen_pars ${ids[$i]} ${names[$i]}"
   done

   # change the audio sink with the switch_sink function
   new_sink_id=$(zenity $zen_pars || echo "")
   [ ! -z $new_sink_id ] && switch_sink $new_sink_id
}

# Use a rofi dmenu to select audio outputs
function switch_rofi()
{
   # get current output id, all output ids and the sink names
   current_id=$(pacmd list-sinks | egrep '\* index:' | egrep -o '[0-9]+$')
   ids=($(pacmd list-sinks | egrep 'index:' | egrep -o '[0-9]+$' | tr '\n' ' '))
   names=($(pacmd list-sinks | egrep 'name:' | cut -d'.' -f2,3,4,5 | tr -d '>'))

   # construct rofi options
   for i in "${!ids[@]}"; do 
      rofiopts="$rofiopts|${ids[$i]} - ${names[$i]}";
      [ ${ids[$i]} = $current_id ] && current_idx=$i
   done

   # show rofi and change the audio sink
   new_sink_id=`echo -e ${rofiopts[@]:1} | rofi -selected-row $current_idx -sep '|' -width 30 -dmenu -i -p sink | awk '{print $1}'`
   [ ! -z $new_sink_id ] && switch_sink $new_sink_id
}

function help_me()
{
   echo "Usage: $0 [gui|rofi|list|<sink name to switch to>]"
}

case "${1:-}" in
   (""|list)   list_sinks        ;;
   ([0-9]*)    switch_sink "$@"  ;;
   (gui)       switch_gui        ;;
   (rofi)      switch_rofi       ;;
   (*)         help_me           ;;
esac
