#!/bin/bash

if [[ -z $(pacman -Qs xclip) ]]; then
  echo "The package xclip is not installed"
  exit 1
fi

if [[ -z $(pacman -Qs rofi) ]]; then
  echo "The package rofi is not installed"
  exit 1
fi

COLOR=`colorpicker --one-shot` 
if [ -n "$COLOR" ]; then
	sleep .2
	VALUE=`echo -e "$COLOR" | rofi -dmenu -width 30 -lines 2 -p format | awk -F': ' '{print $2}'`
	[ -n "$VALUE" ] && echo -n $VALUE | xclip -selection c
fi
