#!/bin/bash

ICON=$HOME/.scripts/assets/lock.png
TMPBG=/tmp/screenshot.png
RES=$(xrandr | grep 'current' | sed -E 's/.*current\s([0-9]+)\sx\s([0-9]+).*/\1x\2/')

# // Scrot is faster for taking the screenshot
# import -window root $TMPBG
scrot $TMPBG

# // FFMPEG is faster on bluring but loses quality
# convert -scale 10% -blur 0x4 -resize 1000% $TMPBG $TMPBG
# convert $TMPBG $ICON -gravity center -composite -matte $TMPBG

ffmpeg -f x11grab -video_size $RES -y -i $DISPLAY -i $ICON -filter_complex "boxblur=15,overlay=(main_w-overlay_w)/2:(main_h-overlay_h)/2" -vframes 1 $TMPBG -loglevel quiet

i3lock -f -i $TMPBG
rm $TMPBG
sleep 1
exit 0
