#!/bin/bash

OPTIONS="Power-off system\nReboot system\nSuspend system\nHibernate system\nLock session\nLogout session\nSwitch user\nReload UI"

# source configuration or use default values
if [ -f $HOME/.config/rofi-power/config ]; then
  source $HOME/.config/rofi-power/config
else
  LAUNCHER="rofi -width 30 -dmenu -i -p option"
  USE_LOCKER="false"
  LOCKER="i3lock_blur"
fi

# Show exit wm option if exit command is provided as an argument
if [ ${#1} -gt 0 ]; then
  OPTIONS="Exit window manager\n$OPTIONS"
fi

option=`echo -e $OPTIONS | $LAUNCHER | awk '{print $1}' | tr -d '\r\n'`
if [ ${#option} -gt 0 ]
then
    case $option in
      Exit)
        eval $1
        ;;
      Power-off)
        systemctl poweroff
        ;;
      Reboot)
        systemctl reboot
        ;;
      Suspend)
        $($USE_LOCKER) && "$LOCKER"; systemctl suspend
        ;;
      Hibernate)
        $($USE_LOCKER) && "$LOCKER"; systemctl hibernate
        ;;
      Lock)
        "$LOCKER"
        ;;
      Logout)
        i3-msg exit
        ;;
      Switch)
        dm-tool switch-to-greeter
        ;;
      Reload)
        RELOAD_UI_OPTIONS="i3\nPolybar\nDunst"
        reload_option=`echo -e $RELOAD_UI_OPTIONS | $LAUNCHER | awk '{print $1}'`
        if [ ${#reload_option} -gt 0 ]
        then
            case $reload_option in
              i3)
                i3-msg restart
                ;;
              Polybar)
                pkill -USR1 polybar
                ;;
              Dunst)
                killall dunst; exec notify-send 'Restarted Dunst'
                ;;
              *)
                ;;
            esac
        fi
        ;;
      *)
        ;;
    esac
fi
