#!/bin/bash

poweroff="襤"
reboot="累"
sleep="鈴"
hibernate="⏾"
lock=""
logout=""
switch=""
reload=""

LOCKER="i3lock-blur"
OPTIONS="$poweroff\n$reboot\n$sleep\n$hibernate\n$lock\n$logout\n$switch\n$reload"
OPTIONS_RELOAD="Polybar\ni3\nDunst\nCompton"
ROFI_TEXT="rofi -lines 10 -width 30 -dmenu -p reload"
ROFI_ICONS="rofi -theme ~/.config/rofi/themes/powermenu.rasi -dmenu -p power-menu"

option=`echo -e $OPTIONS | $ROFI_ICONS | awk '{print $1}'`
[ ${#option} -eq 0 ] && exit 1

case $option in
  	Exit) eval $1 ;;
  	$poweroff) systemctl poweroff ;;
  	$reboot) systemctl reboot ;;
  	$sleep) $LOCKER; systemctl suspend ;;
  	# $hibernate) $($USE_LOCKER) && "$LOCKER"; systemctl hibernate ;;
  	$lock) "$LOCKER" ;;
  	$logout) i3-msg exit ;;
  	$switch) dm-tool switch-to-greeter ;;
  	$reload)
		reload_option=`echo -e $OPTIONS_RELOAD | $ROFI_TEXT | awk '{print $1}'`
		[ ${#reload_option} -eq 0 ] && exit 1
		case $reload_option in
			i3) i3-msg restart ;;
			Polybar) launch-polybar ;;
			Dunst) killall dunst; notify-send 'Restarted Dunst' ;;
			Compton) pkill -USR1 compton ;;
			*) ;;
		esac
		;;
esac