#!/bin/bash

FILE=$(realpath $1)
if [ -z "$1" ] 
then
	echo "No file specified"
	exit 1
fi

if [ -z "$2" ] 
then
	echo "No command specified"
	exit 1
fi

while true; do
  inotifywait -qm --event modify --format '%w' $FILE | $2
done