#!/bin/bash

DELIM=''

POSITIONAL=()
while [[ $# -gt 0 ]]; do
	case $1 in
		-d|--delimiter)
		DELIM="$2"
		shift # past argument
		shift # past value
		;;
		-h|--help)
		echo "Usage: $0 -d/--delimiter '_' 'STRING'"
		exit 0
		;;
		*)
		POSITIONAL+=("$1") # save it in an array for later
		shift # past argument
		;;
	esac
done
set -- "${POSITIONAL[@]}" 

if [[ -z $1 ]]; then
	>&2 echo "Please specify a string"
	exit 1
fi

if [[ -z $DELIM ]]; then
	>&2 echo "Please specify a delimiter (-d)"
	exit 1
fi

IFS='|' read -ra PARTS <<< "$COLOR"
for i in "${PARTS[@]}"; do
	echo "$i"
done