#!/bin/bash
# This script mutes spotify ads, shocker
# Current method: Watching dbus for the current song's artwork, ads don't show any
# There are better alternatives that really block the ads, but since spotify keeps patching on their side, 
# you can always use this to peacefully listen to music without obnoxious ads

dbus-monitor "type='signal',path='/org/mpris/MediaPlayer2',member='PropertiesChanged'" | grep --line-buffered 'string "Metadata"' |
while read -r line ; do
	sink_num=$(pactl list | grep -E '(^Sink Input)|(media.name = \"Spotify\"$)' | awk '/Spotify/ {print a} {a = $0}' | cut -c 13-)
	dbus_metadata=`dbus-send --print-reply --session --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get string:'org.mpris.MediaPlayer2.Player' string:'Metadata' | awk '/string "mpris:artUrl"/{getline; print}'`
	[ -z "$sink_num" ] && continue
	[[ "$dbus_metadata" == *'string ""'* ]] && pactl set-sink-input-mute $sink_num yes || pactl set-sink-input-mute $sink_num no
done &
spotify "$@" &
wait $! &&
test -z "`jobs -p`" || kill `jobs -p` # http://stackoverflow.com/a/2618497
