#!/bin/bash

[ -z "$1" ] && exit 1
# WIN=`xdotool getwindowfocus getwindowname`
WIN=`xprop -id $(xprop -root 32x '\t$0' _NET_ACTIVE_WINDOW | cut -f 2) WM_WINDOW_ROLE`
if [[ $WIN == *"browser"* ]]; then
	xdotool key "$1"
fi